### ISSUE TITLE
Not returning expiry bug

### ISSUE THREAD

**Issue by hc-12** [will-stone/mobx-cookie#1]
In line 106

```
  _expiresToDateTime(expires) {
    if (typeof expires === 'number') {
      const duration = moment.duration(expires, 'days')
      const ms = duration.asMilliseconds()
      return moment()
        .add(ms, 'ms')
        .format()
    } else {
      moment(expires).format()  /* should return here */
    }
  }
```

Consider using typescript, that would have picked up this bug quite easily.

**Comment by will-stone** [comment]
Please give more detail; explain the steps to reproduce the bug. I will not be converting the project to TypeScript.

**Comment by hc-12** [comment]
@will-stone In the function `_expiresToDateTime` you're not returning the value in the `else` block.

**Comment by will-stone** [comment]
Ah ok. Thanks.
