### ISSUE TITLE
Update to MobX v4

### ISSUE THREAD

**Issue by will-stone** [will-stone/mobx-cookie#2]
- [x] Lib 
- [x] Docs

**Comment by t49tran** [comment]
Hi @will-stone, thanks for the great work. I am currently using this library at work, do you still need some help upgrading the library to mobx v4 ?

Also, by upgrading to `mobx` v4, it means that the library will drop support for IE11, is that a concern for you ?

**Comment by will-stone** [comment]
Hi @t49tran, I moved jobs and have been using Redux since. I'm not sure when I'll get around to updating this so feel free to give it a go. Also, despite me originally telling another user that this will never be written in Typescript, I have learnt a lot of TS at my new job so am not adverse to it being changed over. At some point, it would also be nice to ditch the Moment dependency. However, it's difficult to say when I'll start any of these tasks; it's not easy to get involved when I'm not actively using the project.

**Comment by will-stone** [comment]
Hi @t49tran, please see https://github.com/will-stone/mobx-cookie/pull/5 and let me know what you think on the PR.
