### ISSUE TITLE
`Options` params usage in `constructor` and `set`

### ISSUE THREAD

**Issue by t49tran** [will-stone/mobx-cookie#4]
Hi @will-stone, thanks for the great work providing a reactive cookie for `mobx` with `mobx-cookie`.

Recently, I ran through the code as I need to provide a Typescript definition for this library (we have to use Typescript at work). And there is a minor thing I reckon we can do.

```javascript
class MobxCookie {
  /**
   * @param {*} name cookie's name
   * @param {*} options (optional) options to send to js-cookie
   */
  constructor(name, options) {
    this.name = name // name of set cookie
    this.options = options // options to send to js-cookie
    this._timeout = null // internal timer

    extendObservable(this, {
      value: jsCookie.get(name) // observable to keep in-sync with cookie value
    })

    this._syncTimeout()
  }
```

Our constructor is currently accepting a second parameter as `js-cookie` options. However, I don't think we use `this.options` anywhere, instead, if someone want to set the option, he/she needs to do it everytime `set` function is called.

I reckon there are two separated ways we can improve this:

1.) Drop `options` as the second parameter of the constructor.

2.)  `set` function will make use of `this.options` if no `options` param is passed to this function, if there is an `options` param passed, it will be merged and overriden the class `options`.

What do you think ? I am happy to submit a PR for this issue.

**Comment by will-stone** [comment]
Removed `this.options` in https://github.com/will-stone/mobx-cookie/pull/5
