### ISSUE TITLE
Is not working in the IE 11.

### ISSUE THREAD

**Issue by SHorielov** [will-stone/mobx-cookie#8]
Hello everyone!

This library is not working in the IE 11. Because the main file includes ES6 syntax.

**Comment by will-stone** [comment]
Hi. Not that I particularly care about IE but what line is ES6? The tsconfig is set to transpile to es2015: 
https://github.com/will-stone/mobx-cookie/blob/dd5f64991ff5051b7fcccb806273c808527ec278/tsconfig.json#L3

**Comment by SHorielov** [comment]
lib/mobx-cookie.js - all this file is ES6 and when I compile my app, I have trouble with IE. I do not want to turn on compilation the node_modules directory. And I think it's bad.

**Comment by will-stone** [comment]
PRs accepted.

**Comment by will-stone** [comment]
Should be fixed in 2.0.2
