### ISSUE TITLE
Peer dependency warning with mobx v5

### ISSUE THREAD

**Issue by vdh** [will-stone/mobx-cookie#9]
Does `mobx-cookie` have any issue with mobx v5? If not, it would be good to update the peer dependency to allow it.

**Comment by will-stone** [comment]
Hi. To be honest, I haven't used MobX for quite some time. Happy to review a PR if you would to upgrade it and the tests pass.

**Comment by will-stone** [comment]
I've had a look and it looks to work okay with v5. I'll publish a new release shortly.

**Comment by will-stone** [comment]
Updated in v3.0.0
